### ISSUE TITLE
production flag is not recursive as expected

### ISSUE THREAD

**Issue by Raynos** [3rd-Eden/licensing#4]
I would expect `--production` to exclude `devDependencies` recursively all the way down the `npm install` tree.

It does not and includes a bunch of `devDependencies` of my direct `dependencies`

**Comment by 3rd-Eden** [comment]
This should now work with the `1.0` release. I managed to get this: https://gist.github.com/3rd-Eden/ad1d58c0fb4f909e17a4 from the `licensing --name cuid`
